// Command generate_challenge creates the deterministic, public Go-to-C challenge fixture.
//
// The private scalar 2 below is test-only. Production deployment bundle validation
// rejects the small scalars 1, 2, and 3. Generated output contains public material only.
package main

import (
	"bytes"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/sha256"
	"crypto/x509"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"strings"

	"github.com/fxamacker/cbor/v2"
	"github.com/veraison/go-cose"

	"pbns.local/gateway/internal/attestation"
	"pbns.local/gateway/internal/model"
)

const (
	issuedAt = uint64(1_700_000_000_000_000_000)
	expires  = uint64(1_700_000_300_000_000_000)
)

var canonical cbor.EncMode

func init() {
	var err error
	canonical, err = cbor.CanonicalEncOptions().EncMode()
	must(err)
}

func main() {
	if len(os.Args) != 2 {
		panic("usage: generate_challenge OUTPUT-DIR")
	}
	requestID := sequence16(0x10)
	host := sequence32(0x20)
	nonce := sequence32(0x40)
	recipientKID := []byte("recipient-vector-1")
	challengeKID := []byte("challenge-vector-1")
	challenge := attestation.Challenge{
		Context: attestation.Context{
			Domain: attestation.Domain, Version: 1, Service: attestation.ServiceAttestation,
			RequestID: requestID, HostFingerprint: host, Nonce: nonce,
			IssuedAtUnixNS: issuedAt, ExpiresAtUnixNS: expires, Body: []byte{},
		},
		VerifierNonce: nonce,
		Selection:     model.PCRSelection{{Algorithm: 0x000b, Indices: []uint64{0, 2, 4, 7}}},
		RecipientKID:  recipientKID, ExpiresAtUnixNS: int64(expires),
	}
	payload, err := canonical.Marshal(challenge)
	must(err)
	externalAAD, err := canonical.Marshal([]any{
		"PBNS-ATTESTATION-CHALLENGE-SIGN-v1", uint64(1), attestation.ServiceAttestation,
		requestID[:], host[:], nonce[:], recipientKID,
	})
	must(err)

	d := big.NewInt(2) // Test-only fixture scalar; never a deployment key.
	x, y := elliptic.P256().ScalarBaseMult(d.Bytes())
	private := &ecdsa.PrivateKey{
		PublicKey: ecdsa.PublicKey{Curve: elliptic.P256(), X: x, Y: y},
		D:         d,
	}
	signer, err := cose.NewSigner(cose.AlgorithmES256, private)
	must(err)
	message := cose.NewSign1Message()
	message.Headers.Protected.SetAlgorithm(cose.AlgorithmES256)
	message.Headers.Protected[cose.HeaderLabelKeyID] = challengeKID
	message.Payload = payload
	must(message.Sign(bytes.NewReader(bytes.Repeat([]byte{0x42}, 1024)), externalAAD, signer))
	signed, err := message.MarshalCBOR()
	must(err)
	publicDER, err := x509.MarshalPKIXPublicKey(&private.PublicKey)
	must(err)

	var include strings.Builder
	include.WriteString("/* Generated by gateway/internal/attestation/testdata/generate_challenge.go. */\n")
	include.WriteString("/* Public test material only; do not use as deployment trust. */\n")
	writeArray(&include, "pbns_challenge_vector_signed", signed)
	writeArray(&include, "pbns_challenge_vector_public_der", publicDER)
	writeArray(&include, "pbns_challenge_vector_external_aad", externalAAD)
	writeArray(&include, "pbns_challenge_vector_request_id", requestID[:])
	writeArray(&include, "pbns_challenge_vector_host_fingerprint", host[:])
	writeArray(&include, "pbns_challenge_vector_nonce", nonce[:])
	writeArray(&include, "pbns_challenge_vector_recipient_kid", recipientKID)
	writeArray(&include, "pbns_challenge_vector_challenge_kid", challengeKID)
	include.WriteString("static const uint16_t pbns_challenge_vector_selection_algorithms[] = {UINT16_C(0x000b), UINT16_C(0x000b), UINT16_C(0x000b), UINT16_C(0x000b)};\n")
	include.WriteString("static const uint8_t pbns_challenge_vector_selection_indices[] = {UINT8_C(0), UINT8_C(2), UINT8_C(4), UINT8_C(7)};\n")
	fmt.Fprintf(&include, "static const int64_t pbns_challenge_vector_time_earliest = INT64_C(%d);\n", issuedAt+1)
	fmt.Fprintf(&include, "static const int64_t pbns_challenge_vector_time_latest = INT64_C(%d);\n", expires-1)

	must(os.MkdirAll(os.Args[1], 0o755))
	write(os.Args[1], "challenge_vector.inc", []byte(include.String()))
	metadata := fmt.Sprintf("generator=gateway/internal/attestation/testdata/generate_challenge.go\nrebuild=cd pbns/gateway && go run ./internal/attestation/testdata/generate_challenge.go OUTPUT-DIR\nsource_libraries=github.com/fxamacker/cbor/v2,github.com/veraison/go-cose\nprofile=tag-18 canonical COSE_Sign1; protected exactly {1:-7,4:kid}; empty unprotected; canonical challenge payload; exact external AAD\nkey=test-only P-256 public key derived from scalar documented only in generator; generated files contain no private key\nsigned_sha256=%x\npublic_der_sha256=%x\nexternal_aad_sha256=%x\nissued_at_ns=%d\nexpires_at_ns=%d\n", sha256.Sum256(signed), sha256.Sum256(publicDER), sha256.Sum256(externalAAD), issuedAt, expires)
	write(os.Args[1], "provenance.txt", []byte(metadata))
}

func sequence16(start byte) (value [16]byte) {
	for index := range value {
		value[index] = start + byte(index)
	}
	return value
}

func sequence32(start byte) (value [32]byte) {
	for index := range value {
		value[index] = start + byte(index)
	}
	return value
}

func writeArray(output *strings.Builder, name string, value []byte) {
	fmt.Fprintf(output, "static const uint8_t %s[] = {", name)
	for index, current := range value {
		if index%12 == 0 {
			output.WriteString("\n    ")
		}
		fmt.Fprintf(output, "UINT8_C(0x%02x),", current)
		if index == len(value)-1 || index%12 == 11 {
			output.WriteByte('\n')
		} else {
			output.WriteByte(' ')
		}
	}
	output.WriteString("};\n")
}

func write(directory, name string, value []byte) {
	must(os.WriteFile(filepath.Join(directory, name), value, 0o644))
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
