#ifndef PBNS_TEST_TPM20_H
#define PBNS_TEST_TPM20_H

#include <Uefi.h>

#define TPM_ALG_SHA256 UINT16_C(0x000b)
#define TPM_RH_OWNER UINT32_C(0x40000001)
#define TPM_RS_PW UINT32_C(0x40000009)
#define MAX_DIGEST_BUFFER 1024U

typedef UINT8 BYTE;
typedef UINT16 TPMI_ALG_HASH;
typedef UINT32 TPMI_RH_NV_INDEX;
typedef UINT32 TPMI_RH_NV_AUTH;
typedef UINT32 TPMI_SH_AUTH_SESSION;

typedef struct TPMS_PCR_SELECTION {
  UINT16 hash;
  UINT8 sizeofSelect;
  UINT8 pcrSelect[4];
} TPMS_PCR_SELECTION;

typedef struct TPML_PCR_SELECTION {
  UINT32 count;
  TPMS_PCR_SELECTION pcrSelections[8];
} TPML_PCR_SELECTION;

typedef struct TPM2B_DIGEST {
  UINT16 size;
  UINT8 buffer[64];
} TPM2B_DIGEST;

typedef TPM2B_DIGEST TPM2B_NONCE;
typedef TPM2B_DIGEST TPM2B_AUTH;
typedef UINT8 TPMA_SESSION;

typedef struct TPMS_AUTH_COMMAND {
  TPMI_SH_AUTH_SESSION sessionHandle;
  TPM2B_NONCE nonce;
  TPMA_SESSION sessionAttributes;
  TPM2B_AUTH hmac;
} TPMS_AUTH_COMMAND;

typedef struct TPMA_NV {
  UINT32 TPMA_NV_PPWRITE : 1;
  UINT32 TPMA_NV_OWNERWRITE : 1;
  UINT32 TPMA_NV_AUTHWRITE : 1;
  UINT32 TPMA_NV_POLICYWRITE : 1;
  UINT32 TPMA_NV_COUNTER : 1;
  UINT32 TPMA_NV_BITS : 1;
  UINT32 TPMA_NV_EXTEND : 1;
  UINT32 reserved7_9 : 3;
  UINT32 TPMA_NV_POLICY_DELETE : 1;
  UINT32 TPMA_NV_WRITELOCKED : 1;
  UINT32 TPMA_NV_WRITEALL : 1;
  UINT32 TPMA_NV_WRITEDEFINE : 1;
  UINT32 TPMA_NV_WRITE_STCLEAR : 1;
  UINT32 TPMA_NV_GLOBALLOCK : 1;
  UINT32 TPMA_NV_PPREAD : 1;
  UINT32 TPMA_NV_OWNERREAD : 1;
  UINT32 TPMA_NV_AUTHREAD : 1;
  UINT32 TPMA_NV_POLICYREAD : 1;
  UINT32 reserved20_24 : 5;
  UINT32 TPMA_NV_NO_DA : 1;
  UINT32 TPMA_NV_ORDERLY : 1;
  UINT32 TPMA_NV_CLEAR_STCLEAR : 1;
  UINT32 TPMA_NV_READLOCKED : 1;
  UINT32 TPMA_NV_WRITTEN : 1;
  UINT32 TPMA_NV_PLATFORMCREATE : 1;
  UINT32 TPMA_NV_READ_STCLEAR : 1;
} TPMA_NV;

typedef struct TPMS_NV_PUBLIC {
  TPMI_RH_NV_INDEX nvIndex;
  TPMI_ALG_HASH nameAlg;
  TPMA_NV attributes;
  TPM2B_DIGEST authPolicy;
  UINT16 dataSize;
} TPMS_NV_PUBLIC;

typedef struct TPM2B_NV_PUBLIC {
  UINT16 size;
  TPMS_NV_PUBLIC nvPublic;
} TPM2B_NV_PUBLIC;

typedef struct TPM2B_NAME {
  UINT16 size;
  BYTE name[68];
} TPM2B_NAME;

typedef struct TPM2B_MAX_BUFFER {
  UINT16 size;
  BYTE buffer[MAX_DIGEST_BUFFER];
} TPM2B_MAX_BUFFER;

typedef struct TPML_DIGEST {
  UINT32 count;
  TPM2B_DIGEST digests[8];
} TPML_DIGEST;

#endif
