#ifndef PBNS_LWIPOPTS_H
#define PBNS_LWIPOPTS_H

#define NO_SYS 1
#define LWIP_RAW 1
#define LWIP_SOCKET 0
#define LWIP_NETCONN 0
#define LWIP_DHCP 1
#define LWIP_DNS 1
#define LWIP_NETIF_HOSTNAME 1
#define LWIP_NETIF_STATUS_CALLBACK 1

#define LWIP_ALTCP 0

#define MEM_LIBC_MALLOC 0
#define MEM_ALIGNMENT 4
#define MEM_SIZE (64U * 1024U)
#define MEMP_NUM_TCP_PCB 4
#define MEMP_NUM_TCP_SEG 32
#define TCP_MSS 1460
#define PBUF_POOL_SIZE 16
#define PBUF_POOL_BUFSIZE 1536
#define TCP_WND (16U * 1024U)
#define TCP_SND_BUF (8U * 1024U)
#define TCP_QUEUE_OOSEQ 0
#define LWIP_TCP_KEEPALIVE 1
#define LWIP_STATS 0

#endif
